#!/bin/bash
#
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# Prepend the commit message with the ticket number.
if [ -z "$3" ] && [ "$2" != "merge" ]; then
  branch_name=$(git symbolic-ref -q HEAD | sed -e 's/refs\/heads\///' | sed -e 's/\(^[A-Z]{3,}-[0-9]\+\).*/\1/i')
  echo -n "$branch_name: "|cat - $1 > /tmp/out && mv /tmp/out $1
fi

# Comments out the "Conflicts:" part of a merge commit.
case "$2,$3" in
  merge,)
    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;
  *) ;;
esac

