dot-install package xsel
dot-install package arandr
dot-install package xscreensaver
dot-install package xscreensaver-data-extra
dot-install package xscreensaver-gl
dot-install package xscreensaver-gl-extra
dot-install package xscreensaver-screensaver-bsod
dot-install package feh
dot-install package dmenu
dot-install package i3-wm
dot-install package i3-wm-dbg
dot-install package konsole
dot-install package evince
dot-install package gimp
dot-install package libreoffice-writer
dot-install package libreoffice-calc
dot-install package dconf-editor
