alias gs="git status"
alias gd="git diff"
alias gds="git diff --staged"
alias ga="git add"
alias gc="git commit"
alias gcb="git checkout -b"
alias gll="git log --oneline"
alias gbl="git branch"
alias gf="git fetch"
alias gp="git pull"
alias grh="git reset HEAD"
alias gb="git checkout"

alias gpom="git push origin master"
alias gpot="git push origin --tags"
